-- Total revenue generated by film category
WITH revenue AS (
    SELECT global_rental_id, amount
    FROM {{ ref('fact_revenue') }}
),
rentals AS (
    SELECT global_rental_id, global_film_id
    FROM {{ ref('fact_rental') }}
),
films AS (
    SELECT global_film_id, COALESCE(category_name, 'Unknown') AS category_name
    FROM {{ ref('dim_film') }}
)
SELECT
    f.category_name,
    SUM(r.amount) AS total_revenue
FROM revenue r
JOIN rentals ren ON r.global_rental_id = ren.global_rental_id
JOIN films f ON ren.global_film_id = f.global_film_id
GROUP BY 1
ORDER BY total_revenue DESC