version: 2

sources:
  - name: pagila
    database: RAW_DB
    schema: PAGILA
    config:
      loaded_at_field: last_update
      freshness:
        warn_after: {count: 24, period: hour}
        error_after: {count: 168, period: hour}
    tables:
      - name: film
      - name: actor
      - name: film_actor
      - name: category
      - name: film_category
      - name: rental
      - name: customer
      - name: inventory
      - name: payment
      - name: address
      - name: city

  - name: sakila
    database: RAW_DB
    schema: SAKILA
    config:
      loaded_at_field: last_update
      freshness:
        warn_after: {count: 24, period: hour}
        error_after: {count: 168, period: hour}
    tables:
      - name: film
      - name: actor
      - name: film_actor
      - name: category
      - name: film_category
      - name: rental
      - name: customer
      - name: inventory
      - name: payment
      - name: address
      - name: city